#ifndef __MODBUS_FILTER_H
#define __MODBUS_FILTER_H

struct flow_policy {
  __u32 src_ip;
  __u32 dst_ip;
};

enum counter_index {
  COUNTER_TOTAL = 0,
  COUNTER_NON_IPV4,
  COUNTER_NON_TCP,
  COUNTER_NON_MODBUS,
  COUNTER_RESPONSE_ALLOWED,
  COUNTER_POLICY_MISS_ALLOWED,
  COUNTER_READ_ALLOWED,
  COUNTER_WRITE_DROPPED,
  COUNTER_UNKNOWN_DROPPED,
  COUNTER_MALFORMED_DROPPED,
  COUNTER_MAX
};

#endif
